# Generated by Django 5.0.1 on 2024-02-08 06:20

from django.db import migrations, models
from apps.products.models import Product
from django.conf import settings


def create_default_products():
    Product.objects.create(title='Mens Casual Shirt',description='Casual shirt for mens',price=499,category='Shirt',image=settings.BASE_DIR+'media/default/product_images/mens_casual_shirt.jpg',gender='M')
    Product.objects.create(title='Mens Oversized Shirt',description='Oversized shirt for mens',price=699,category='Shirt',image=settings.BASE_DIR+'media/default/product_images/oversized_shirt.jpg',gender='M')
    Product.objects.create(title='Embroided Shirt',description='Embroided shirt for mens',price=699,category='Shirt',image=settings.BASE_DIR+'media/default/product_images/embroided_shirt_men.webp',gender='M')
    Product.objects.create(title='Formal Pant',description='Formal Pant for mens',price=699,category='Pant',image=settings.BASE_DIR+'media/default/product_images/mens_formal_pant.webp',gender='M')
    Product.objects.create(title='Embroided Shirt',description='Embroided shirt for women',price=699,category='Shirt',image=settings.BASE_DIR+'media/default/product_images/embroided_shirt_women.webp',gender='F')
    Product.objects.create(title='Tunic Shirt',description='Tunic shirt for women',price=699,category='Shirt',image=settings.BASE_DIR+'media/default/product_images/tunic_shirt_women.webp',gender='F')
    Product.objects.create(title='Oversized Shirt',description='Oversized shirt for women',price=699,category='Shirt',image=settings.BASE_DIR+'media/default/product_images/oversized_shirt_women.webp',gender='F')
    Product.objects.create(title='Formal Shirt',description='Formal Pant for women',price=699,category='Pant',image=settings.BASE_DIR+'media/default/product_images/women_pant.webp',gender='F')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('inventory', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(create_default_products),
    ]
