# Generated by Django 5.0.1 on 2024-02-07 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_alter_customer_tailor'),
        ('orders', '0003_remove_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('fail', 'Failed')], default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_images', models.FileField(upload_to='')),
                ('design_images', models.ImageField(blank=True, null=True, upload_to='')),
                ('notes', models.TextField(blank=True, max_length=200, null=True)),
                ('unit_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('requested_date', models.DateField()),
                ('status', models.CharField(choices=[('NS', 'Not Stitched'), ('S', 'Stitching'), ('C', 'Stitched')], max_length=100)),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
