# Generated by Django 5.0.1 on 2024-02-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_customer_order_order_date_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='design_images',
            new_name='design_image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cloth_images',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cloth_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Stitched'), ('S', 'Stitching'), ('C', 'Stitched')], default='NS', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.PositiveIntegerField(),
        ),
    ]
