# Generated by Django 5.0.1 on 2024-02-08 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_tailor'),
        ('products', '0005_rename_name_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cloth_image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='design_image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
