# Generated by Django 5.0.1 on 2024-02-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orderitem_cloth_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('PRE', 'PREPAID'), ('POST', 'POSTPAID')], max_length=50, null=True),
        ),
    ]
