# Generated by Django 5.0.1 on 2024-02-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_orderitem_tailor_order_tailor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='urgent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
