# Generated by Django 5.0.1 on 2024-02-15 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_customer_alter_order_tailor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('NS', 'Not Stitched'), ('S', 'Stitching'), ('C', 'Stitched')], default='NS', max_length=100, null=True),
        ),
    ]
