# Generated by Django 5.0.1 on 2024-02-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderitem_order_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('Not Stitched', 'Not Stitched'), ('Stitching', 'Stitching'), ('Stitched', 'Stitched')], default='Not Stitched', max_length=100, null=True),
        ),
    ]
