# Generated by Django 5.0.1 on 2024-02-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_delivered',
            field=models.CharField(blank=True, choices=[('Delivered', 'Delivered'), ('Not Delivered', 'Not Delivered')], default='Not Delivered', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stitched_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
