# Generated by Django 5.0.1 on 2024-02-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderitem_is_delivered_orderitem_stitched_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
