# Generated by Django 5.0.1 on 2024-02-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_rename_stitched_date_orderitem_stitched_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('Not-Stitched', 'Not-Stitched'), ('Stitching', 'Stitching'), ('Delivered', 'Delivered'), ('Stitched', 'Stitched')], default='Not-Stitched', max_length=100, null=True),
        ),
    ]
