# Generated by Django 5.0.1 on 2024-03-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_order_options_remove_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['requested_date']},
        ),
    ]
