# Generated by Django 5.0.1 on 2024-01-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_tailor'),
        ('orders', '0003_remove_order_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
