# Generated by Django 5.0.1 on 2024-02-01 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='customers.customer')),
                ('neck', models.FloatField(blank=True, null=True)),
                ('chest', models.FloatField(blank=True, null=True)),
                ('waist', models.FloatField(blank=True, null=True)),
                ('hips', models.FloatField(blank=True, null=True)),
                ('thigh', models.FloatField(blank=True, null=True)),
                ('knee', models.FloatField(blank=True, null=True)),
                ('calf', models.FloatField(blank=True, null=True)),
                ('sleeve', models.FloatField(blank=True, null=True)),
                ('back', models.FloatField(blank=True, null=True)),
                ('waistband', models.FloatField(blank=True, null=True)),
                ('outseam', models.FloatField(blank=True, null=True)),
                ('inseam', models.FloatField(blank=True, null=True)),
                ('ankle', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
