# Generated by Django 5.0.1 on 2024-02-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_customer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile',
            field=models.ImageField(blank=True, default='profile-user.jpeg', null=True, upload_to='profile/'),
        ),
    ]
