# Generated by Django 5.0.1 on 2024-02-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_customer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile',
            field=models.ImageField(blank=True, default='profile-user.png', null=True, upload_to='profile/'),
        ),
    ]
