# Generated by Django 5.0.1 on 2024-03-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0003_alter_tailoruser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailoruser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
