# Generated by Django 5.0.1 on 2024-02-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_amount_transaction_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
