# Generated by Django 5.0.1 on 2024-01-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_orders_remove_customer_transactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
